### ISSUE TITLE
bug: Warning: Command \@parboxrestore  has changed.

### ISSUE THREAD

**Issue by larkinrt** [walkergareth/latex#1]
I get the following warning when running the code from the documentation:

```
test.tex|| LaTeX Warning: Command \@parboxrestore  has changed.
```

To reproduce, download convtran.sty into the directory, call it with \usepackage{} and run the following:
 
```
\begin{convtran}
  \turn{D:} O:h (I k-)=
  \turn{A:} =Dz that make any sense to you?
  \turn{C:} Mn mh. I don’ even know who she is.
  \turn{A:} She’s that’s, the Sister Kerrida, [who,
  \turn{D:} ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[.hhh
  \turn{D:} Oh [\underline{that’s} the one you to:ld [me you bought
  \turn{C:} ~~~[Oh-~~~~~~~~~~~~~~~~~~~~~~[
  \turn{A:} ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[\underline{Ye:h}
\end{convtran}
```

It still compiles and I can safely ignore it for now.

Also I just want to say this is an excellent package and I hope it can be included in ctan / texlive eventually.

**Comment by walkergareth** [comment]
I'm glad you are finding the package useful.  Can you confirm that you get that warning when you run this minimal example? 
```
\documentclass{article}
\usepackage{convtran}
\begin{document}
\begin{convtran}
  \turn{D:} O:h (I k-)=
  \turn{A:} =Dz that make any sense to you?
  \turn{C:} Mn mh. I don’ even know who she is.
  \turn{A:} She’s that’s, the Sister Kerrida, [who,
  \turn{D:} ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[.hhh
  \turn{D:} Oh [\underline{that’s} the one you to:ld [me you bought
  \turn{C:} ~~~[Oh-~~~~~~~~~~~~~~~~~~~~~~[
  \turn{A:} ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[\underline{Ye:h}
\end{convtran}
\end{document}
```
I ask because I don't get the warning on that document (though I can make the warning appear if I change some other things).

**Comment by larkinrt** [comment]
Ah my fault, I should have tested it more before reporting.

The minimal configuration you provided worked fine.

It seems to be a conflict with  ```\usepackage{csquotes}``` which is required for the apa7 class. The following also compiles without warning, it is only when ```\usepackage{csquotes}``` is added that it becomes an issue:

```
\documentclass[man]{apa7}
\usepackage[style=apa]{biblatex}
\usepackage{convtran}
\title{test}
\begin{document}
\maketitle
\section{Test}
\subsection{Test}
Here is an example of a Jeffersonian transcription using \verb!contrav.sty!.
\begin{convtran}
  \turn{D:} O:h (I k-)=
  \turn{A:} =Dz that make any sense to you?
  \turn{C:} Mn mh. I don’ even know who she is.
  \turn{A:} She’s that’s, the Sister Kerrida, [who,
  \turn{D:} ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[.hhh
  \turn{D:} Oh [\underline{that’s} the one you to:ld [me you bought
  \turn{C:} ~~~[Oh-~~~~~~~~~~~~~~~~~~~~~~[
  \turn{A:} ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[\underline{Ye:h}
\end{convtran}
\end{document}
```

As an aside, it might be beneficial to mention in section 2.3 of the documentation that gb4e needs to be called after convtran for it to work properly for the numbered examples.

**Comment by walkergareth** [comment]
Yes, it seems like the warning appears if csquotes is loaded before lineno ([SE](https://tex.stackexchange.com/a/447159)). I've put a note in the documentation, and added a note about gb4e.
